# Generated by Django 5.1 on 2024-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sep_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.CharField(max_length=20)),
                ('STANDARD_SETTING', models.CharField(max_length=20)),
                ('ORGANIZATION', models.CharField(max_length=200)),
                ('IPRD_REFERENCE', models.CharField(max_length=200)),
                ('DIPG_DISPLAY_NUMBER', models.IntegerField()),
                ('IPRD_SIGNATURE_DATE', models.DateField()),
                ('PATENT_OWNER', models.CharField(max_length=200)),
                ('ETPR_ACRONYM', models.CharField(max_length=200)),
                ('STANDARD', models.CharField(max_length=200)),
                ('ILLUSTRATIVE_PART', models.CharField(max_length=200)),
                ('Ess_To_Project', models.BooleanField(default=False)),
                ('Ess_To_Standard', models.BooleanField(default=False)),
                ('App_pub_pat_Number', models.CharField(max_length=200)),
                ('Application_Number', models.CharField(max_length=200)),
                ('Publication_Number', models.CharField(max_length=200)),
                ('Patent_Number', models.CharField(max_length=200)),
                ('COUNTRY_CODE', models.CharField(max_length=200)),
                ('Tye', models.CharField(max_length=200)),
                ('Radio_Tech', models.CharField(max_length=200)),
                ('DIPG_EXTERNAL_ID', models.CharField(max_length=200)),
                ('COMMITTEE', models.CharField(max_length=200)),
                ('RECOMMENDATION', models.CharField(max_length=200)),
                ('Technology', models.CharField(max_length=200)),
                ('Sub_Technology', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('DIPG_ID', models.IntegerField(max_length=50)),
                ('DIPG_PATF_ID', models.IntegerField(max_length=50)),
                ('PATT_ID', models.IntegerField(max_length=50)),
                ('Inventor', models.CharField(max_length=100)),
            ],
        ),
    ]
