# Generated by Django 5.1 on 2024-08-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sep_dashboard',
            name='ORGANIZATION',
        ),
    ]
