# Generated by Django 5.1 on 2024-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0002_remove_sep_dashboard_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sep_dashboard',
            name='App_pub_pat_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Application_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='COMMITTEE',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='COUNTRY_CODE',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_DISPLAY_NUMBER',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_EXTERNAL_ID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_ID',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_PATF_ID',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='ETPR_ACRONYM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='ILLUSTRATIVE_PART',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='IPRD_REFERENCE',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='IPRD_SIGNATURE_DATE',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Inventor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='PATENT_OWNER',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='PATT_ID',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Patent_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Publication_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='RECOMMENDATION',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Radio_Tech',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='STANDARD',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='STANDARD_SETTING',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='S_No',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Sub_Technology',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Technology',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Tye',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
