# Generated by Django 5.1 on 2024-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0003_alter_sep_dashboard_app_pub_pat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='DIPG_PATF_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='PATT_ID',
            field=models.IntegerField(blank=True),
        ),
    ]
