# Generated by Django 5.1 on 2024-09-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0004_alter_sep_dashboard_dipg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sep_dashboard',
            old_name='ETPR_ACRONYM',
            new_name='Current_Assignee',
        ),
    ]
