# Generated by Django 5.1 on 2024-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0006_remove_sep_dashboard_radio_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sep_dashboard',
            old_name='Tye',
            new_name='Type',
        ),
    ]
