# Generated by Django 5.1 on 2024-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0007_rename_tye_sep_dashboard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Ess_To_Project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Ess_To_Standard',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
