# Generated by Django 5.1 on 2024-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0008_alter_sep_dashboard_ess_to_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Ess_To_Project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sep_dashboard',
            name='Ess_To_Standard',
            field=models.BooleanField(default=False),
        ),
    ]
