# Generated by Django 5.1 on 2024-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0010_alter_sep_dashboard_app_pub_pat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sep_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPRD_REFERENCE', models.CharField(blank=True, max_length=1000)),
                ('PATENT_OWNER', models.CharField(blank=True, max_length=1000)),
                ('Current_Assignee', models.CharField(blank=True, max_length=1000)),
                ('Application_Number', models.CharField(blank=True, max_length=1000)),
                ('Publication_Number', models.CharField(blank=True, max_length=1000)),
                ('RECOMMENDATION', models.CharField(blank=True, max_length=1000)),
                ('Sub_Technology', models.CharField(blank=True, max_length=1000)),
                ('Inventor', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
