# Generated by Django 5.1 on 2024-11-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0011_sep_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sep_Search',
        ),
    ]
