# Generated by Django 5.1 on 2024-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0013_sep_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='sep_search',
            name='Patent_Number',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
