# Generated by Django 5.1 on 2024-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0016_sep_dashboard_inside_sep__standar_7af442_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
