# Generated by Django 5.1 on 2024-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0017_excludeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sep_dashboard',
            name='IPRD_SIGNATURE_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
